# Ejemplo de datos de entrada y prediccion

In [1]:
import pandas as pd
import tensorflow as tf
import numpy as np
import sys
import warnings
warnings.filterwarnings('ignore')
sys.path.append('../')
from src.utils.LSTMPipeline import LSTMPipeline

## Ejemplo con Cartago

In [2]:
datos_entrada_cartago = pd.read_csv('../data/raw/ultimos_9_registros_cartago.csv', index_col=0)
datos_entrada_cartago

,Fecha,Hora,Delito,Victima,Edad,Sexo,Nacionalidad,Canton,Conteo
9088,2026-02-10,0,HOMICIDIO,PERSONA,Mayor de edad,HOMBRE,COSTA RICA,CARTAGO,5
9089,2026-02-10,3,Sin delitos,Sin delitos,Sin delitos,Sin delitos,Sin delitos,Sin delitos,0
9090,2026-02-10,6,Sin delitos,Sin delitos,Sin delitos,Sin delitos,Sin delitos,Sin delitos,0
9091,2026-02-10,9,ASALTO,PERSONA,Mayor de edad,MUJER,Desconocido,CARTAGO,1
9092,2026-02-10,12,ASALTO,VEHICULO,Mayor de edad,HOMBRE,COSTA RICA,CARTAGO,1
9093,2026-02-10,15,Sin delitos,Sin delitos,Sin delitos,Sin delitos,Sin delitos,Sin delitos,0
9094,2026-02-10,18,ROBO DE VEHICULO,VEHICULO,Mayor de edad,MUJER,COSTA RICA,CARTAGO,1
9095,2026-02-10,21,ASALTO,PERSONA,Mayor de edad,HOMBRE,NICARAGUA,LA UNION,1
9096,2026-02-11,0,HURTO,EDIFICACION,Mayor de edad,MUJER,COSTA RICA,CARTAGO,1

In [3]:
pipeline = LSTMPipeline.load('../src/models/CARTAGO/pipeline.pkl')
X_new = pipeline.transform_predict(datos_entrada_cartago)


modelo = tf.keras.models.load_model('../src/models/CARTAGO/LSTM-CARTAGO.keras')

y_pred_scaled = modelo.predict(X_new)
prediccion = pipeline.inverse_transform_y(y_pred_scaled)
print(f'Se estiman {int(np.round(prediccion)[0][0])} delitos según las condiciones dadas.')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 238ms/step
Se estiman 0 delitos según las condiciones dadas.

## Ejemplo con San José

In [4]:
datos_entrada_sj = pd.read_csv('../data/raw/ultimos_9_registros_sanjose.csv', index_col=0)
datos_entrada_sj

,Fecha,Hora,Delito,Victima,Edad,Sexo,Nacionalidad,Canton,Conteo
9319,2026-03-10,21,ROBO DE VEHICULO,VEHICULO,Mayor de edad,HOMBRE,COSTA RICA,MONTES DE OCA,8
9320,2026-03-11,0,ROBO DE VEHICULO,PERSONA,Mayor de edad,HOMBRE,COSTA RICA,DESAMPARADOS,10
9321,2026-03-11,3,ROBO DE VEHICULO,VEHICULO,Adulto Mayor,MUJER,COSTA RICA,MORAVIA,2
9322,2026-03-11,6,ASALTO,PERSONA,Mayor de edad,HOMBRE,COSTA RICA,SAN JOSE,2
9323,2026-03-11,9,ASALTO,PERSONA,Mayor de edad,HOMBRE,COSTA RICA,SAN JOSE,1
9324,2026-03-11,12,Sin delitos,Sin delitos,Sin delitos,Sin delitos,Sin delitos,Sin delitos,0
9325,2026-03-11,15,HURTO,PERSONA,Menor de edad,MUJER,COSTA RICA,PEREZ ZELEDON,1
9326,2026-03-11,18,TACHA DE VEHICULO,VEHICULO,Mayor de edad,HOMBRE,COSTA RICA,CURRIDABAT,1
9327,2026-03-11,21,ASALTO,PERSONA,Mayor de edad,HOMBRE,EL SALVADOR,SAN JOSE,1

In [5]:
pipeline = LSTMPipeline.load('../src/models/SAN JOSE/pipeline.pkl')
X_new = pipeline.transform_predict(datos_entrada_sj)


modelo = tf.keras.models.load_model('../src/models/SAN JOSE/LSTM-SAN JOSE.keras')

y_pred_scaled = modelo.predict(X_new)
prediccion = pipeline.inverse_transform_y(y_pred_scaled)
print(f'Se estiman {int(np.round(prediccion)[0][0])} delitos según las condiciones dadas.')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 226ms/step
Se estiman 5 delitos según las condiciones dadas.